
CREATE UNIQUE INDEX CUSTOMER_NAME_INDEX ON CUSTOMER (FName);
CREATE UNIQUE INDEX PAYMENT_DATE_INDEX ON PAYMENT (PaymentDate);
CREATE UNIQUE INDEX PACKAGE_CATEGORY_INDEX ON PACKAGE (EventCategory);
CREATE UNIQUE INDEX PLACE_CITY_INDEX ON PLACE (PCity);
CREATE UNIQUE INDEX PLACE_CHALLENGE_INDEX ON PLACE (ChallengeLevel);
CREATE UNIQUE INDEX EVENT_DATE_INDEX ON EVENT (EventDate);
CREATE UNIQUE INDEX PHOTO_DATE_INDEX ON PHOTO (EventDate);
CREATE UNIQUE INDEX CUSTOMER_ATTENDANCE_INDEX ON CUSTOMER_ATTENDS_EVENTS (EventDate);
CREATE UNIQUE INDEX DATE_INDEX ON CUSTOMER_ACQUIRES_PACKAGES (DateOfAcquisition);
CREATE UNIQUE INDEX PAYMENT_PACKAGE_INDEX ON PAYMENT_IS_LINKED_TO_PACKAGE (PackageID);
CREATE UNIQUE INDEX PHONE_CUSTOMER_INDEX ON CUSTOMER_TELEPHONE_NUMBERS (CustomerID);


